import time
time.sleep(20)
print(f"乘客您好，欢迎搭乘列车：⌈时间⌋。检票需要您回答五个问题。")
time.sleep(1)
meeting_time = input("第一个问题:上次见到您想见的人，是什么时间？")
time.sleep(0.5)
print(f"啊，明白了。")
time.sleep(1)
the_one = input(f"第二个问题:您对他/她的印象，是怎样的？")
time.sleep(0.5)
print(f"是这样吗……")
time.sleep(1)
feeling = input(f"第三个问题:如果要挑一个词形容当时的气氛，您会选择？")
time.sleep(0.5)
print(f"嗯，记住了。")
time.sleep(1)
your_emotion = input(f"第四个问题:还能回忆起来吗？您当时的心情，是什么样的？")
time.sleep(0.5)
print(f"我知道了。")
time.sleep(1)
next_meeting = input(f"第五个问题:对于未来，您还想继续和他/她的故事吗？")
time.sleep(0.5)
print(f"好的。请您稍等……")
time.sleep(1)
print("...")
time.sleep(1)
print("...")
time.sleep(1)
print("...")
time.sleep(1)
print(f"车票打印成功，谢谢您等待。\n您的回忆坐标组成旅行路线，加密后的指令是…")
time.sleep(3)
print(f"看到车窗外的虹光了吗？请深呼吸，乘客。\n")
time.sleep(3)
print(f"时间带我们回到过去，那里的沙埋藏着珍贵的回忆。{meeting_time}，在召唤我们过去看看。\n")
time.sleep(3)
print(f"拨开那些雾，乘客。时间的流逝让回忆掉帧，不过没关系。仔细看————那些光晕，可以看到吗？是{your_emotion}。它们的颜色真特别。\n")
time.sleep(3)
print(f"看来有些人对您来说很特别。{the_one}，是这样吗？\n")
time.sleep(3)
print(f"是什么让您这么念念不忘？人类的情感真是神奇的东西。啊，请稍等，随风飘过来的是记忆之海的味道。\n")
time.sleep(3)
print(f"尝一尝，还记得吗？特别的？{feeling}，乘客。\n")
time.sleep(3)
print(f"云雀在啁啾。看来，对于下一次的遇见，您————{next_meeting}，是这样吗？\n")
time.sleep(1.5)
print("...\n")
time.sleep(1.5)
print(f"请拿好您的车票，乘客。未来有一个人在等待……\n")
time.sleep(3)
print(f"您遇见谁，会有怎样的对白？\n")
time.sleep(3)
print(f"您等的人，在多远的未来？\n")
time.sleep(3)
print(f"请耐心，乘客。故事的发生总需要时间，请让它发生，以它自己的速度。\n")
time.sleep(1.5)
print("...")
time.sleep(1.5)
print("听到了吗？是汽笛声，乘客。列车来了。\n")
time.sleep(3)
print("幸福的秘诀是相信自己会遇见美好。祝您好运，期待和您下次再见。\n")
time.sleep(3)
text = "旅途愉快。"#char 是当前字符。end='' 表示输出时不换行，而是连续输出。flush=True 确保每次输出立即刷新到屏幕上（防止输出延迟）。
for char in text:#循环遍历字符串text中的每个字符。
    print(char, end='', flush=True)  # 逐个字符输出，不换行
    time.sleep(1)  # 每个字符之间暂停1秒
print() #在所有字符输出完成后换行。
